version: '3.7'

services:
  mysql:
    container_name: task_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_mysql
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - task_mysql_network

networks:
  task_mysql_network:
